substitutions:
  _REGION: europe-west1
  _REPO: tacticeye

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.worker
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/worker:latest
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/worker:latest
